- name: Install nginx
  ansible.builtin.dnf:
    name: nginx
    state: present

- name: copying expense config file
  ansible.builtin.template:
    src: expense.conf
    dest: /etc/nginx/default.d/expense.conf

- name: Import Common Role - App Pre-Requisites
  ansible.builtin.import_role:
    name: common
    tasks_from: app-prereq
  vars:
    app_dir: /usr/share/nginx/html
    component: frontend

- name: Start nginx service
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: yes

- name: Import elk Role - Filebeat
  ansible.builtin.import_role:
    name: elk
    tasks_from: filebeat

- name: Import Prometheus - node-exporter
  ansible.builtin.import_role:
    name: prometheus
    tasks_from: node-exporter


- name: Installing New Relic Agent
  ansible.builtin.shell: curl -Ls https://download.newrelic.com/install/newrelic-cli/scripts/install.sh | bash && sudo NEW_RELIC_API_KEY=NRAK-9TX1KXJIMBJCIX8GYMI2P67EK13 NEW_RELIC_ACCOUNT_ID=4466271 /usr/local/bin/newrelic install -y -n infrastructure-agent-installer

- name: Install New Relic NGINX Agent
  ansible.builtin.dnf:
    name: nri-nginx
    state: installed

- name: Copying new-relic Nginx Agent config file
  ansible.builtin.template:
    src: nr-nginx.yml
    dest: /etc/newrelic-infra/integrations.d/nginx-config.yml

- name: Copying Newrelic Nginx Agent Log Shipper Config file
  ansible.builtin.template:
    src: nr-nginx-log.yml
    dest: /etc/newrelic-infra/logging.d/nginx-log.yml
