- name: Install nginx
  ansible.builtin.dnf:
    name: nginx
    state: present

- name: copying expense config file
  ansible.builtin.template:
    src: expense.conf
    dest: /etc/nginx/default.d/expense.conf

- name: Import Common Role - App Pre-Requisites
  ansible.builtin.import_role:
    name: common
    tasks_from: app-prereq
  vars:
    app_dir: /use/share/nginx/html
    component: frontend

- name: Start nginx service
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: yes

- name: Import elk Role - Filebeat
  ansible.builtin.import_role:
    name: elk
    tasks_from: filebeat

- name: Import Prometheus - node-exporter
  ansible.builtin.import_role:
    name: prometheus
    tasks_from: node-exporter

- name: Import Grafana - Dashboard Creation
  ansible.builtin.import_role:
    name: grafana

- name: Generate Alert YAML File
  ansible.builtin.template:
    src: alert-rule.yml
    dest: /tmp/{{component}}-{{env}}.yml

- name: upload file to s3
  amazon.aws.s3_object:
    bucket: d76-prometheus-instance-bucket
    object: "{{component}}-{{env}}.yml"
    src: /tmp/{{component}}-{{env}}.yml





