- name: Generate Alert YAML File
  ansible.builtin.template:
    src: alert-rule.yml
    dest: /tmp/{{component}}-{{env}}.yml

- name: upload file to s3
  ansible.builtin.shell: aws s3 cp /tmp/{{component}}-{{env}}.yml s3://d76-prometheus-alert-rules/{{component}}-{{env}}.yml
    # amazon.aws.s3_object:
    #  bucket: d76-prometheus-alert-rules
    # object: "{{component}}-{{env}}.yml"
    #src: /tmp/{{component}}-{{env}}.yml
    #mode: put
  #permission: bucket-owner-full-control

- name: Trigger prometheus reload job
  ansible.builtin.shell: curl -u {{ lookup('amazon.aws.aws_ssm','jenkins.username', region='us-east-1' ) }}:{{ lookup('amazon.aws.aws_ssm','jenkins.password', region='us-east-1' ) }} "http://172.31.43.184:8080/job/prometheus-reload/build?token=prometheus"


