- name:  Copy Prometheus Configuration
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml

- name: Copy Alert Rules
  ansible.builtin.template:
    src: alert-rules.yml
    dest: /opt/prometheus/alert-rules.yml

- name: List All files in Bucket
  aws_s3:
    bucket: d76-prometheus-instance-bucket
    mode: list
  register: out

- name: Download all the Objects from s3 Bucket Having Alert Files
  aws_s3:
    bucket: d76-prometheus-instance-bucket
    mode: get
    object: "{{ item }}"
    dest: "/opt/prometheus/alert-rules/{{ item|basename }}"
  loop: "{{ out.s3_keys }}"

- name: Reload Prometheus
  ansible.builtin.shell:  kill -1 $( ps -ef | grep /opt/prometheus/prometheus | grep -v grep |awk '{print $2}')


- name: Copy alert Manager Configuration
  ansible.builtin.template:
    src: alertmanager.yml
    dest: /opt/alertmanager/alertmanager.yml

- name: Reload Alert Manager
  ansible.builtin.shell:  kill -1 $( ps -ef | grep /opt/alertmanager/alertmanager | grep -v grep |awk '{print $2}')


