- name: Delete old app directory
  ansible.builtin.file:
    path: "{{ app_dire}}"
    state: absent

- name: Create App Directory
  ansible.builtin.file:
    path: "{{ app_dir }}"
    state: directory

- name: Download and extract Application content
  ansible.builtin.unarchive:
    src: https://expense-artifacts.s3.amazonaws.com/{{component}}.zip
    dest: "{{ app_dir }}"
    remote_src: yes